### ISSUE TITLE
[FEAT]: change website logo position

### ISSUE THREAD

**Issue by devvsakib** [ezequielbugnon/interview-challenges#5]
I think it will look better if website logo moved to left corner
![image](https://user-images.githubusercontent.com/88339569/232197146-0a4c94da-29ff-4601-954f-e4a5ce1cda70.png)

**Comment by swapn652** [comment]
Hey, I would like to work on this if it's still open

**Comment by ezequielbugnon** [comment]
It's open, now I'll assign you the issue
