### ISSUE TITLE
[FEAT]: implement darkmode theme

### ISSUE THREAD

**Issue by devvsakib** [ezequielbugnon/interview-challenges#6]
**Is your feature request related to a problem? Please describe.**
Now a days, dark mode is part of everywebsite

**Describe the solution you'd like**
Implement dark mode theme

Dark Mode:
![image](https://user-images.githubusercontent.com/88339569/232197397-b7ae7adc-ab54-4388-90aa-2aafaa413362.png)
Lightmode
![image](https://user-images.githubusercontent.com/88339569/232197276-2dee40bb-83c6-4256-a152-bdb18a8c2f15.png)

**Additional context**
Anyone can work on this issue, but please read contribution guideline first

**Comment by swapn652** [comment]
Can I work on this?
