### ISSUE TITLE
Remove scrollbar 

### ISSUE THREAD

**Issue by ezequielbugnon** [ezequielbugnon/interview-challenges#8]
This scrollbar below should not exist, please remove

![image](https://user-images.githubusercontent.com/60440435/236539883-fc1ecf8e-b4b0-4abe-b211-c7045d2f17d9.png)

**Comment by giri-madhan** [comment]
Hi @ezequielbugnon , Can I work on this task?

**Comment by giri-madhan** [comment]
I have added a PR https://github.com/ezequielbugnon/interview-challenges/pull/9 which fixes this issue. @ezequielbugnon
